//REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
//LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
//GET POST FOR MAIN SCREEN
export const GETPOSTFORMAINSCREEN_REQUEST = 'GETPOSTFORMAINSCREEN_REQUEST'
export const GETPOSTFORMAINSCREEN_SUCCESS = 'GETPOSTFORMAINSCREEN_SUCCESS'
export const GETPOSTFORMAINSCREEN_ERROR = 'GETPOSTFORMAINSCREEN_ERROR'
// GET POST APPROVED
export const GETPOSTAPPROVED_REQUEST = 'GETPOSTAPPROVED_REQUEST'
export const GETPOSTAPPROVED_SUCCESS = 'GETPOSTAPPROVED_SUCCESS'
export const GETPOSTAPPROVED_ERROR = 'GETPOSTAPPROVED_ERROR'
//GET POST UNAPPROVED
export const GETPOSTUNAPPROVED_REQUEST = 'GETPOSTUNAPPROVED_REQUEST'
export const GETPOSTUNAPPROVED_SUCCESS = 'GETPOSTUNAPPROVED_SUCCESS'
export const GETPOSTUNAPPROVED_ERROR = 'GETPOSTUNAPPROVED_ERROR'
// CREATE POST 
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'
// GET LOCATION IN THE CIRCLE
export const GET_LOCATION_INTHECIRCLE_REQUEST = 'GET_LOCATION_INTHECIRCLE_REQUEST'
export const GET_LOCATION_INTHECIRCLE_SUCCESS = 'GET_LOCATION_INTHECIRCLE_SUCCESS'
export const GET_LOCATION_INTHECIRCLE_ERROR   = 'GET_LOCATION_INTHECIRCLE_ERROR'
